### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling.

### ISSUE THREAD

**Issue by xfguo-ucas** [sanghoon/pva-faster-rcnn#56]
Hello All,
I am trying to run this command: 

cd $FRCN_ROOT
./tools/test_net.py --net models/pvanet/pva9.1/PVA9.1_ImgNet_COCO_VOC0712.caffemodel --def models/pvanet/pva9.1/faster_rcnn_train_test_21cls.pt --cfg models/pvanet/cfgs/submit_1019.yml --gpu 0

I encountered this error,
Traceback (most recent call last):
  File "./tools/test_net.py", line 13, in <module>
    from fast_rcnn.test import test_net
  File "/home/mordekaiser/pva-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/mordekaiser/pva-faster-rcnn/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
  File "__init__.pxd", line 155, in init nms.gpu_nms (nms/gpu_nms.cpp:4184)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

Please help me through this. thanks

**Comment by xfguo-ucas** [comment]
I download data again fix the problem, maybe the data was corruption.
: )
